### ISSUE TITLE
support barebone xcodeproj

### ISSUE THREAD

**Issue by tami5** [tami5/xbase#65]
Although intentionally I wanted to stay away from supporting a non-generative Xcode project due to how it require reopening Xcode every time the project working directory structure changes, but this is something important, it would be nice to just clone a xcodeproj and be able to navigate it.

Maybe there is a tool that would enable wave the requirement of reopening Xcode project when the directory change. We'll see.

- [ ] Parse `.xcodeproj` and extract targets, schemas,
- [ ] #45 
- [ ] Make `Project` and enum with `XBare` variant indicating an non-generative xcodeproj.

**Comment by tami5** [comment]
After implementing the initial xcodeproj parser I had an epiphany, 

> What if instead of depending on and creating a data parser for project.yml or Project.swift, we only process xcodeproj? 

Now that is something worth going after. it will not only free xbass from maintaining multiple project generators but also drop the requirement of having a generator in the first place as parsed data could be possible to modify and encoded back to something xcodebuild can process 

Sound like first major release 😳 will a lot sooner then I expected!!!

**Comment by tami5** [comment]
Unfortunately, due to single threaded requirement of [xcodeproj](https://github.com/tami5/xcodeproj) this issue will be postponed few more days till I drop single threaded requirement from `xcodeproj`. 🙄 I should've integrated `xcodeproj` here in the early development phases

**Comment by amanuel2** [comment]
Is a solution to this issue still ongoing? Doesn't seem to work on example objective c xcodeproj's
