### ISSUE TITLE
Readme: mention how to setup xbase plugin 

### ISSUE THREAD

**Issue by michaelnew** [tami5/xbase#79]
Sorry if I'm abusing the issue tracker here, but either something is broken or I don't know what I'm doing.

I added the plugin via vim-plug like this, and it appears to install just fine (`make install` succeeds at least): 
```vim
call plug#begin('~/.vim/plugged')
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
Plug 'tami5/xbase', { 'do': 'make install' }
call plug#end()
```

The project *is* built with xcodegen and has a `project.yml` file at it's root. But when I edit a file in the project directory, nothing happens. There's also no xbase log or socket opened in `/tmp`.

Am I missing a config setting somewhere? I realize I installed this with vim-plug rather than packer, but I would have expected it to work the same.

**Comment by tami5** [comment]
oh no worries, please do abuse the issue tracker it helps us improve😅. 

In this case, It's actually my fault, I totally forgot to mention the setup function required to be called at startup

Try `require'xbase'.setup({}) either passing empty table or table of options overwriting the defaults specified in the readme.

I'll try to add it tomorrow, thanks

**Comment by chrstphfrtz** [comment]
I will just add to this comment that it may be a good idea to also add cargo/rustup as a requirement for ```make install``` to work. It makes total sense (being a rust project and compiling it etc.) but I think it helps to have it listed as a prerequisite or something.

**Comment by michaelnew** [comment]
Sorry, finally got a chance to mess with this again and yes, works great now. So thank you 😁

I'll just mention for anyone else like me who's trying to get things working: it seems like things don't work unless `xcodebuild` succeeds, and that has been super fiddly for me. Running `xcodebuild build` sometimes works, sometimes doesn't, sometimes it works if I build in Xcode and *then* build from cli, sometimes it fails the first time but works the second, sometimes it works after an `xcodebuild clean` and sometimes not, and so on.

Typical non-deterministic Xcode stuff.

**Comment by tami5** [comment]
> Sorry, finally got a chance to mess with this again and yes, works great now. So thank you 😁
> 
> I'll just mention for anyone else like me who's trying to get things working: it seems like things don't work unless `xcodebuild` succeeds, and that has been super fiddly for me. Running `xcodebuild build` sometimes works, sometimes doesn't, sometimes it works if I build in Xcode and _then_ build from cli, sometimes it fails the first time but works the second, sometimes it works after an `xcodebuild clean` and sometimes not, and so on.
> 
> Typical non-deterministic Xcode stuff.


Yes, there are some much things that could result in build failure other than the code source having an issue. Recently, I made changes to compile command to make sure it never fails due to signing issue. Yes, definitely Xcode and xcodebuild is not developer friendly. Hopefully with time we could minimize this issues
